name: deploy-actions

on:
  push:
    branches: [release]

jobs:
  ci:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker images
        run: |
          docker-compose -f docker-compose.prod.yaml build
          docker-compose -f docker-compose.prod.yaml push
  
  cd:
    needs: [ci]
    runs-on: ubuntu-20.04

    steps:
      - name: Docker Image Pull And Container Run
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            docker compose down
            docker system prune -a
            docker compose pull
            docker compose up -d